Add FileTree
fyne-io/fyne-x pull request #2
Opened 2020-12-08 18:04 UTC by stuartmscott

- Extends widget.Tree for displaying a file system hierarchy
- Enables Go Modules

2020-12-08 20:40 UTC, Jacalz requested changes
The icon in the README looks broken, but it looks good to me otherwise.

2020-12-09 15:28 UTC, Jacalz submitted a review, later dismissed
I don't have a clue about what the Sorter() function does, but apart from that it looks very good :)

2020-12-09 16:09 UTC, andydotxyz requested changes
Agreed this looks like a great addition, but let's resolve the broken tests before landing

2020-12-10 01:14 UTC, AlbinoGeek commented
That's the wrong import path isn't it? (in the example code in the `README`)

2020-12-10 22:07 UTC, stuartmscott commented
@AlbinoGeek can you elaborate? That code compiles and runs just fine

2020-12-10 22:10 UTC, AlbinoGeek commented
@stuartmscott Based on the [`README`](../blob/master/README.md) I figured the import paths to be used were:

`fyne.io/x/fyne/layout`
`fyne.io/x/fyne/widget`

2020-12-10 22:17 UTC, stuartmscott commented
Ah I see what you mean, tho `fyne.io/x/fyne/widget` is a vanity URL for `github.com/fyne-io/fyne-x/widget` so 'wrong' is a little strong. Will fix

2020-12-10 22:20 UTC, AlbinoGeek commented
Good point! I apologize for the wording. I figured with the way `go-import-meta` is, the "vanity URL" could do a little more than that (such as versioning, etc.) -- but I see at the moment it is not doing any of these things.

2020-12-10 22:23 UTC, stuartmscott commented
No worries :)

This PR is ready for review, tho it can't be merged because the pesky FileIcon is missing from the golden image

2021-02-08 20:29 UTC, stuartmscott commented on widget/filetree.go
>  			c.Objects[1].(*widget.FileIcon).Refresh()
Ideally Refresh wouldn't be needed at all once SetURI is fixed

2021-02-08 20:33 UTC, stuartmscott commented on widget/filetree.go
>  			c.Objects[1].(*widget.FileIcon).Refresh()
Done

2021-02-08 20:56 UTC, andydotxyz approved these changes

2021-04-07 10:22 UTC, andydotxyz approved these changes
Sweet!

2021-04-07 15:10 UTC, merged