ResponsiveCanvasObject interface + object hiding
fyne-io/fyne-x pull request #59
Opened 2023-05-17 19:55 UTC by aodhan-domhnaill

Two changes,

- Interface for ResponsiveCanvasObject so that custom types can be used
- Resizing behavior is handled by the interface method
- Add hiding behavior so object can be hidden if the window shrinks

First two are self explanatory. The hiding behavior is something that I personally wanted so I can have a "summary/detail" view in a table widget I will am working on.

Let me know if you think I should move the hiding behavior out into another interface.

2023-05-17 20:57 UTC, andydotxyz commented
I don't think the concept of "ResponsiveCanvasObject" works - only widgets can be extended.
The primitive canvas objects and the container type do not support extending. The code will compile but the objects will not appear (because the graphics driver does not know how to draw them).

2023-06-04 12:44 UTC, aodhan-domhnaill commented
@andydotxyz I don't know the details, but it works :)

```
func (rt *ResponsiveTable) AddRow(ele ...fyne.CanvasObject) {
	l := layout.NewResponsiveLayout()
	for i, e := range ele {
		row := layout.Responsive(
			e,
			rt.rowConstants[i]*rt.sizeTotals[0],
			rt.rowConstants[i]*rt.sizeTotals[1],
			rt.rowConstants[i]*rt.sizeTotals[2],
			rt.rowConstants[i]*rt.sizeTotals[3],
		)
		if i > 1 {
			row.Hidable(true)
		}
		l.Add(row)
	}
	rt.tableContainer.Add(l)
}
```

The behavior is what I would expect too. The details in my table row hide when I shrink the window

2023-06-04 12:48 UTC, aodhan-domhnaill commented
By the way, I'm building widgets and layouts with the goal to get to https://react-bootstrap-table.github.io/react-bootstrap-table2/. I've been breaking them into separate PRs as I slowly build them out.

If you have a different approach to managing PRs, let me know.

2023-06-04 14:22 UTC, andydotxyz commented
> @andydotxyz I don't know the details, but it works :)
> 
> 
> 
> ```
> 
> func (rt *ResponsiveTable) AddRow(ele ...fyne.CanvasObject) {
> 
> 	l := layout.NewResponsiveLayout()
> 
> 	for i, e := range ele {
> 
> 		row := layout.Responsive(
> 
> 			e,
> 
> 			rt.rowConstants[i]*rt.sizeTotals[0],
> 
> 			rt.rowConstants[i]*rt.sizeTotals[1],
> 
> 			rt.rowConstants[i]*rt.sizeTotals[2],
> 
> 			rt.rowConstants[i]*rt.sizeTotals[3],
> 
> 		)
> 
> 		if i > 1 {
> 
> 			row.Hidable(true)
> 
> 		}
> 
> 		l.Add(row)
> 
> 	}
> 
> 	rt.tableContainer.Add(l)
> 
> }
> 
> ```
> 
> 
> 
> The behavior is what I would expect too. The details in my table row hide when I shrink the window

I'm not sure that the code sample shows usage of the `ResponsiveCanvasObject` that I was unsure of?

2023-06-04 16:07 UTC, aodhan-domhnaill commented
Changed it to extending Widget. Maybe that's better

2023-06-06 20:18 UTC, andydotxyz commented
Thanks.

What I am curious about is whether this has to be tied to window size? It breaks the container model we use everywhere else.
Can't it just use the container size and conform with the widget/layout contract without the need for connecting to the current window and assuming it has maths based on the whole space?

2023-06-09 06:39 UTC, aodhan-domhnaill commented
https://github.com/fyne-io/fyne-x/blob/master/layout/responsive.go#L112

It's in the existing code. I didn't like it either, but didn't want to break your existing functionality.

2023-11-14 07:32 UTC, andydotxyz requested changes
I'm not sure why this change introduces so many new API. Also it seems to move the container layout logic into widgets which isn't how containers generally work.

Perhaps @metal3d can comment on the general idea of hiding at thresholds and how it fits into responsive overall, but this implementation feels like it may not be the best way?

2024-09-24 13:48 UTC, andydotxyz commented
Can we close this in favour of #79 my @metal3d ?

2024-09-24 15:30 UTC, aodhan-domhnaill commented
Closing in favor of #79

2024-09-24 15:30 UTC, closed without merging