Add different selection modes to Calendar (Single, Multi, Range)
fyne-io/fyne-x pull request #66
Opened 2023-06-22 12:32 UTC by PucklaJ

This PR adds different modes of selection to the calendar.

+ CalendarSingle
This is the same as the current mode. Only one date can be selected at once.
+ CalendarMulti
Multiple random dates can be selected at the same time
+ CalendarRange
Select a beginning and end to select all dates in between those dates.

To achieve this change some compatibility breaking changes had to be made:

1. `SelectedDates` field has beend added to the calendar struct
Here all dates that the user will select are stored no matter what mode has been chosen. This can also be freely manipulated as it is an exported field. When calling `Refresh` the display is updated.
2. `OnSelected` has been replaced by `OnChanged`
The `OnChanged` callback is now called everytime the user presses a button and the selected dates are changed
3. Selected date buttons are highlighted using the HighImportance
Since there isn't another way to give buttons custom colors right now. I used the Importance system to signal the user which dates he has selected. And if a button is not selected it uses the previous LowImportance.

2023-07-03 14:14 UTC, andydotxyz requested changes
I would expect this could be made backward compatible by defaulting to single data selection. Then a field or method could change this after constructor returns?

2023-07-17 08:48 UTC, PucklaJ commented
I changed the constructor to default to single mode. It is more backwards compatible, but not completely since the callback requires a slice instead of a single variable.

2023-10-04 13:13 UTC, andydotxyz commented
Perhaps `OnSelected` is still valid, as is. And a new callback (OnChanged?) might provide the ability for the slice/range types of callback?

2023-12-14 10:33 UTC, PucklaJ commented
@andydotxyz I readded the OnSelected callback and changed the default constructor to the way it was before. For the Single mode it works the same way and for the Multi and Range mode I called the callback everytime a date is pressed and part of the selected dates.

2024-09-24 13:41 UTC, andydotxyz commented
I'm very sorry this PR got left for a while without re-review.
The `Calendar` has since been promoted to the `fyne` repo on develop branch - would you be interested in re-creating the work over there. We are working on some time input widgets that provide a single "input field" type approach which might make it easier to see how multi-select calendar fits in?

2025-01-04 07:40 UTC, closed without merging