Add about dialog and window for helping apps make a pretty about screen
fyne-io/fyne-x pull request #87
Opened 2024-03-25 22:00 UTC by andydotxyz

Matching the parallax look in develop version of fyne_demo.
Looks sweet :)

![about](https://github.com/fyne-io/fyne-x/assets/294436/225ebb4a-35d7-4a92-a96c-865887d81b2b)

2024-03-25 22:47 UTC, Jacalz commented
Nice stuff. Kind of related to https://github.com/Jacalz/rymdport/issues/143 which I opened recently.

Something about having the version above seems strange to me. Maybe we can consider something like the following screenshot (smaller text below the icon)?

![](https://private-user-images.githubusercontent.com/25466657/312250682-b6ef5832-5b4c-46d8-8098-61ee22540ba7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE0MDcwMjIsIm5iZiI6MTcxMTQwNjcyMiwicGF0aCI6Ii8yNTQ2NjY1Ny8zMTIyNTA2ODItYjZlZjU4MzItNWI0Yy00NmQ4LTgwOTgtNjFlZTIyNTQwYmE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI1VDIyNDUyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAyMDU4NzYxYzY0OGViNTE2MDg1ZjQ1NWE1ODQ4N2I1ZWM5ODgyZjdhYWRhY2M2MWJjZjBlODYwMjY1NjY2YTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rAvIA-3dYT1NixaCeihydjRZhe7MMbNKLMGsg-bxD2g)

2024-03-25 22:58 UTC, Jacalz requested changes

2024-03-25 22:58 UTC, Jacalz commented on dialog/about.go
> +func ShowAbout(content string, links []*widget.Hyperlink, a fyne.App, w fyne.Window) {
Can we get a `NewAbout()` so it is possible to not have to recreate it each time?

2024-03-25 22:58 UTC, Jacalz commented on dialog/about.go
> +func aboutContent(content string, links []*widget.Hyperlink, a fyne.App) fyne.CanvasObject {
This function is huge. Can you make it a bit smaller and make readable?

2024-03-25 22:58 UTC, Jacalz commented on dialog/about.go
> +		pos = fyne.NewPos(0, -pad)
```suggestion
		pos.Y = -pad
```

2024-03-25 22:58 UTC, Jacalz commented on dialog/about.go
> +	}
```suggestion
	if u.top {
		size.Y += pad
	}
	if u.bottom {
		size.Y += pad
	}
```

2024-03-26 09:05 UTC, andydotxyz commented
That's all addressed now (and new images added to show)

2024-03-26 11:47 UTC, Jacalz approved these changes
Thanks. This is looking perfect now. I haven't been able to test it locally (due to being away from my laptop) but the code looks great.

2024-03-26 13:10 UTC, merged